/**
 * Curated list of companies with free public job board APIs.
 * Sources: Bloomberry (bloomberry.com/data/greenhouse, bloomberry.com/data/ashby),
 * Toolsberry (toolsberry.com/companies-using-greenhouse), Echoloc (echoloc.ai).
 * Greenhouse: board token from boards.greenhouse.io/{token}
 * Ashby: job board name from jobs.ashbyhq.com/{name}
 */

export const GREENHOUSE_BOARDS: { token: string; company: string }[] = [
  // Verified from Bloomberry
  { token: "appfire", company: "Appfire" },
  { token: "unilever", company: "Unilever" },
  { token: "transcendinc", company: "Transcend" },
  { token: "accessibe", company: "accessiBe" },
  { token: "athomehealth", company: "At Home Healthcare" },
  { token: "skyloom", company: "Skyloom" },
  { token: "machinifyinc", company: "Machinify" },
  { token: "elliemd", company: "EllieMD" },
  { token: "eaglebusinesscredit", company: "Eagle Business Credit" },
  { token: "beaconpowerservices", company: "Beacon Power Services" },
  { token: "eccintegrator", company: "ECC" },
  { token: "braunhageybordenllp", company: "BraunHagey" },
  { token: "rtwinvestments", company: "RTW Investments" },
  // Toolsberry + well-known tech
  { token: "stripe", company: "Stripe" },
  { token: "notion", company: "Notion" },
  { token: "figma", company: "Figma" },
  { token: "airtable", company: "Airtable" },
  { token: "plaid", company: "Plaid" },
  { token: "reddit", company: "Reddit" },
  { token: "coinbase", company: "Coinbase" },
  { token: "dropbox", company: "Dropbox" },
  { token: "discord", company: "Discord" },
  { token: "square", company: "Block" },
  { token: "spotify", company: "Spotify" },
  { token: "twilio", company: "Twilio" },
  { token: "instacart", company: "Instacart" },
  { token: "brex", company: "Brex" },
  { token: "datadog", company: "Datadog" },
  { token: "mongodb", company: "MongoDB" },
  { token: "elastic", company: "Elastic" },
  { token: "rubrik", company: "Rubrik" },
  { token: "segment", company: "Segment" },
  { token: "snowflake", company: "Snowflake" },
  { token: "hubspot", company: "HubSpot" },
  { token: "zendesk", company: "Zendesk" },
  { token: "asana", company: "Asana" },
  { token: "canva", company: "Canva" },
  { token: "gitlab", company: "GitLab" },
  { token: "hashicorp", company: "HashiCorp" },
  { token: "vercel", company: "Vercel" },
  { token: "robinhood", company: "Robinhood" },
  { token: "doordash", company: "DoorDash" },
  { token: "affirm", company: "Affirm" },
  { token: "cloudflare", company: "Cloudflare" },
  { token: "warbyparker", company: "Warby Parker" },
  { token: "airbnb", company: "Airbnb" },
  { token: "pinterest", company: "Pinterest" },
  { token: "snap", company: "Snap" },
  { token: "uber", company: "Uber" },
  { token: "lyft", company: "Lyft" },
  { token: "grubhub", company: "Grubhub" },
  { token: "coursera", company: "Coursera" },
  { token: "duolingo", company: "Duolingo" },
  { token: "quizlet", company: "Quizlet" },
  { token: "lattice", company: "Lattice" },
  { token: "gusto", company: "Gusto" },
  { token: "rippling", company: "Rippling" },
  { token: "calendly", company: "Calendly" },
  { token: "loom", company: "Loom" },
  { token: "atlassian", company: "Atlassian" },
  { token: "box", company: "Box" },
  { token: "slack", company: "Slack" },
  { token: "zoom", company: "Zoom" },
  { token: "docusign", company: "DocuSign" },
  { token: "okta", company: "Okta" },
  { token: "splunk", company: "Splunk" },
  { token: "crowdstrike", company: "CrowdStrike" },
  { token: "palantir", company: "Palantir" },
  { token: "rivian", company: "Rivian" },
  { token: "cruise", company: "Cruise" },
  { token: "waymo", company: "Waymo" },
  { token: "nuro", company: "Nuro" },
  { token: "scale", company: "Scale AI" },
  { token: "anthropic", company: "Anthropic" },
  { token: "openai", company: "OpenAI" },
  { token: "cohere", company: "Cohere" },
  { token: "huggingface", company: "Hugging Face" },
  { token: "stability", company: "Stability AI" },
  { token: "replicate", company: "Replicate" },
  { token: "langchain", company: "LangChain" },
  { token: "pinecone", company: "Pinecone" },
  { token: "weaviate", company: "Weaviate" },
  { token: "neon", company: "Neon" },
  { token: "supabase", company: "Supabase" },
  { token: "planetscale", company: "PlanetScale" },
  { token: "cockroachlabs", company: "Cockroach Labs" },
  { token: "confluent", company: "Confluent" },
  { token: "dbt", company: "dbt" },
  { token: "fivetran", company: "Fivetran" },
  { token: "airbyte", company: "Airbyte" },
  { token: "retool", company: "Retool" },
  { token: "webflow", company: "Webflow" },
  { token: "vimeo", company: "Vimeo" },
  { token: "grammarly", company: "Grammarly" },
  { token: "linear", company: "Linear" },
  { token: "coda", company: "Coda" },
  { token: "miro", company: "Miro" },
  { token: "monday", company: "Monday.com" },
  { token: "smartsheet", company: "Smartsheet" },
  { token: "salesforce", company: "Salesforce" },
  { token: "adobe", company: "Adobe" },
  { token: "servicenow", company: "ServiceNow" },
  { token: "workday", company: "Workday" },
  { token: "sap", company: "SAP" },
  { token: "oracle", company: "Oracle" },
  { token: "intel", company: "Intel" },
  { token: "amd", company: "AMD" },
  { token: "nvidia", company: "NVIDIA" },
  { token: "qualcomm", company: "Qualcomm" },
  { token: "broadcom", company: "Broadcom" },
  { token: "meta", company: "Meta" },
  { token: "netflix", company: "Netflix" },
  { token: "twitter", company: "X" },
  { token: "chime", company: "Chime" },
  { token: "sofi", company: "SoFi" },
  { token: "nubank", company: "Nubank" },
  { token: "klarna", company: "Klarna" },
  { token: "checkout", company: "Checkout.com" },
  { token: "marqeta", company: "Marqeta" },
  { token: "finix", company: "Finix" },
  { token: "nerdwallet", company: "NerdWallet" },
  { token: "zeplin", company: "Zeplin" },
  { token: "clover", company: "Clover" },
  { token: "circleci", company: "CircleCI" },
  { token: "codility", company: "Codility" },
  { token: "revenuecat", company: "RevenueCat" },
  { token: "builderio", company: "Builder.io" },
  { token: "talkspace", company: "Talkspace" },
  { token: "anduril", company: "Anduril" },
  { token: "humaninterest", company: "Human Interest" },
  { token: "span", company: "SPAN" },
  { token: "cerebras", company: "Cerebras" },
  { token: "fedex", company: "FedEx" },
  { token: "goodyear", company: "Goodyear" },
  { token: "diamondfoundry", company: "Diamond Foundry" },
];

export const ASHBY_BOARDS: { name: string; company: string }[] = [
  // Verified from Bloomberry
  { name: "pyyne", company: "Pyyne" },
  { name: "pointfive", company: "PointFive" },
  { name: "lightspeedhq", company: "Lightspeed Commerce" },
  { name: "docplanner", company: "Docplanner" },
  { name: "applied", company: "Applied Intuition" },
  { name: "subsets", company: "Subsets" },
  { name: "overview", company: "Overview AI" },
  { name: "clair", company: "Clair" },
  { name: "praecipio", company: "Praecipio" },
  { name: "morning-consult", company: "Morning Consult" },
  { name: "genies", company: "Genies" },
  { name: "databook", company: "Databook" },
  { name: "stitch", company: "Stitch" },
  { name: "kins", company: "Kins" },
  { name: "freewill", company: "FreeWill" },
  { name: "forerunner", company: "Forerunner" },
  { name: "aviator", company: "Aviator Health" },
  { name: "1x", company: "1x Technologies" },
  { name: "hinge-health", company: "Hinge Health" },
  { name: "healthgorilla", company: "Health Gorilla" },
  // Well-known Ashby customers
  { name: "ashby", company: "Ashby" },
  { name: "linear", company: "Linear" },
  { name: "retool", company: "Retool" },
  { name: "fathom", company: "Fathom" },
  { name: "vessel", company: "Vessel" },
  { name: "mitto", company: "Mitto" },
  { name: "baselane", company: "Baselane" },
  { name: "temporal", company: "Temporal" },
  { name: "readme", company: "ReadMe" },
  { name: "deel", company: "Deel" },
  { name: "rutter", company: "Rutter" },
  { name: "superhuman", company: "Superhuman" },
  { name: "mux", company: "Mux" },
  { name: "tonal", company: "Tonal" },
  { name: "runway", company: "Runway" },
  { name: "rippling", company: "Rippling" },
  { name: "clerk", company: "Clerk" },
  { name: "outer", company: "Outer" },
  { name: "postscript", company: "Postscript" },
  { name: "ramp", company: "Ramp" },
  { name: "mercury", company: "Mercury" },
  { name: "brex", company: "Brex" },
  { name: "woven", company: "Woven" },
  { name: "hightouch", company: "Hightouch" },
  { name: "census", company: "Census" },
  { name: "hex", company: "Hex" },
  { name: "sigma", company: "Sigma Computing" },
  { name: "mode", company: "Mode" },
  { name: "perplexity", company: "Perplexity" },
  { name: "cursor", company: "Cursor" },
  { name: "replit", company: "Replit" },
  { name: "codesandbox", company: "CodeSandbox" },
  { name: "vercel", company: "Vercel" },
  { name: "netlify", company: "Netlify" },
  { name: "sentry", company: "Sentry" },
  { name: "datadog", company: "Datadog" },
  { name: "highlight", company: "Highlight" },
  { name: "posthog", company: "PostHog" },
  { name: "amplitude", company: "Amplitude" },
  { name: "mixpanel", company: "Mixpanel" },
  { name: "heap", company: "Heap" },
  { name: "launchdarkly", company: "LaunchDarkly" },
  { name: "split", company: "Split" },
  { name: "optimizely", company: "Optimizely" },
  { name: "twilio", company: "Twilio" },
  { name: "sendgrid", company: "SendGrid" },
  { name: "loops", company: "Loops" },
  { name: "resend", company: "Resend" },
  { name: "postmark", company: "Postmark" },
  { name: "segment", company: "Segment" },
  { name: "iterable", company: "Iterable" },
  { name: "braze", company: "Braze" },
  { name: "klaviyo", company: "Klaviyo" },
  { name: "attentive", company: "Attentive" },
];
